data_platform_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: "data-platform-dev-477621"
      location: "EU"
      schema: 'dbt_test'
      threads: 4
      timeout_seconds: 300
      method: "{{ env_var('DBT_AUTH_METHOD', 'oauth') }}"
      impersonate_service_account: "{{ env_var('SERVICE_ACCOUNT', '') }}"
      token: "{{ env_var('CLOUDSDK_AUTH_ACCESS_TOKEN', '') }}"
    prod:
      type: bigquery
      project: "data-platform-prod-477621"
      location: "EU"
      schema: 'dbt_test'
      threads: 4
      timeout_seconds: 300
      method: "{{ env_var('DBT_AUTH_METHOD', 'oauth') }}"
      impersonate_service_account: "{{ env_var('SERVICE_ACCOUNT', '') }}"
      token: "{{ env_var('CLOUDSDK_AUTH_ACCESS_TOKEN', '') }}"