#!/bin/bash

# Activate your venv first
source .venv/bin/activate

# Add to your venv activation script
echo 'export DBT_PROFILES_DIR=/Users/serhii/PycharmProjects/data-platform-dbt/.dbt' >> .venv/bin/activate

# Deactivate and reactivate
deactivate
source .venv/bin/activate
