FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy static docs generated by GitHub Actions
COPY ../target/ ./static/

COPY app.py .

EXPOSE 8080
CMD ["python", "app.py"]
